kind: pipeline
type: docker
name: Build multiarch image

platform:
  os: linux
  arch: arm64

steps:
  - name: Build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      experimental: true
      platforms:
        - linux/amd64
        - linux/arm64
        - linux/arm
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/nginx-rtmp
      tags:
        - latest
