kind: pipeline
type: docker
name: Build x86 image

steps:
  - name: Build
    image: thegeeklab/drone-docker-buildx
    privileged: true
    settings:
      platforms:
        - linux/amd64
        - linux/arm64
      mirror:
        from_secret: DOCKER_MIRROR
      username:
        from_secret: DOCKER_USERNAME
      password:
        from_secret: DOCKER_PASSWORD
      repo: aricodes/nginx-rtmp
      tags:
        - latest
        - amd64-latest
